In [1]:
# Wikipedia
# https://pt.wikipedia.org/wiki/Lista_de_unidades_federativas_do_Brasil_por_popula%C3%A7%C3%A3o

In [2]:
# Importa a biblioteca pandas para manipulação e análise de dados.
import pandas as pd

# Importa a classe StringIO do módulo io para trabalhar com operações de I/O em strings.
from io import StringIO

In [3]:
dados_populacao_ibge = """
Posição	Unidade federativa	População(Censo de 2022)[2]	População(Censo de 2010)[3]	Mudança	% da pop. total	País comparável (habitantes)

1	 São Paulo	44 411 238	41 262 199	+7.63%	21,88%	 Argentina (46 621 847)
2	 Minas Gerais	20 538 718	19 597 330	+4.81%	10,11%	 Burquina Fasso (20 903 273)
3	 Rio de Janeiro	16 054 524	15 989 929	+0.40%	7,91%	Camboja Camboja (16 718 965)
4	Bahia	14 141 626	14 016 906	+0.89%	6,96%	 Zimbabwe (14 862 924)
5	 Paraná	11 444 380	10 444 526	+9.57%	5,64%	 Tunísia (11 818 619)
6	 Rio Grande do Sul	10 882 965	10 693 929	+1.76%	5,36%	Portugal Portugal (10 343 066)
7	 Pernambuco	9 058 931	8 796 448	+2.98%	4,46%	 Áustria (9 006 398)
8	 Ceará	8 794 957	8 452 381	+4.05%	4,33%	 Papua-Nova Guiné (8 947 024)
9	Pará Pará	8 121 025	7 581 051	+7.12%	4,1%	 Suíça (8 654 622)
10	 Santa Catarina	7 610 361	6 248 436	+21.78%	3,75%	Laos Laos (7 749 595)
11	 Goiás	7 056 495	6 003 788	+17.51%	3,47%	 Bulgária (6 948 445)
12	 Maranhão	6 775 805	6 574 789	+3.05%	3,34%	 Bulgária (6 948 445)
13	 Paraíba	3 974 687	3 766 528	+5.52%	1,96%	 Geórgia (3 989 167)
14	 Amazonas	3 941 613	3 483 985	+13.12%	1,94%	 Geórgia (3 989 167)
15	 Espírito Santo	3 833 712	3 514 952	+9.06%	1,89%	 Geórgia (3 989 167)
16	 Mato Grosso	3 658 649	3 035 122	+20.55%	1,8%	 Geórgia (3 989 167)
17	 Rio Grande do Norte	3 302 729	3 168 027	+4.24%	1,63%	 Uruguai (3 473 730)
18	 Piauí	3 271 199	3 118 360	+4.88%	1,61%	 Bósnia e Herzegovina (3 280 819)
19	 Alagoas	3 127 683	3 120 494	+0.23%	1,54%	 Mónaco (3 278 290)
20	 Distrito Federal	2 817 381	2 570 160	+9.62%	1,39%	 Armênia (2 963 243)
21	 Mato Grosso do Sul	2 757 013	2 449 024	+12.56%	1,36%	 Albânia (2 877 797)
22	 Sergipe	2 209 558	2 068 017	+6.86%	1,09%	 Gabão (2 225 734)
23	 Rondônia	1 581 196	1 562 409	+1.19%	0,78%	 Bahrein (1 701 575)
24	 Tocantins	1 511 460	1 383 445	+9.25%	0,74%	 Guiné Equatorial (1 402 985)
25	 Acre	830 018	733 559	+13.15%	0,41%	 Comores (869 601)
26	 Amapá	733 759	669 526	+9.56%	0,36%	 Guiné Equatorial (786 552)
27	 Roraima	636 707	450 479	+41.26%	0,31%	 Montenegro (649 335)
"""

In [4]:
# Cria um buffer de texto a partir da string `dados_populacao_ibge`.
dados_populacao_io = StringIO(dados_populacao_ibge)

# Lê os dados do buffer como um DataFrame, usando tabulação como separador.
novos_dados = pd.read_csv(dados_populacao_io, sep="\t", thousands=".", decimal=",")

# Remove linhas com NaN e atualiza `novos_dados` diretamente.
novos_dados.dropna(inplace=True)

# Exibe o DataFrame `novos_dados`.
novos_dados

,Posição,Unidade federativa,População(Censo de 2022)[2],População(Censo de 2010)[3],Mudança,% da pop. total,País comparável (habitantes)
0,1,São Paulo,44 411 238,41 262 199,+7.63%,"21,88%",Argentina (46 621 847)
1,2,Minas Gerais,20 538 718,19 597 330,+4.81%,"10,11%",Burquina Fasso (20 903 273)
2,3,Rio de Janeiro,16 054 524,15 989 929,+0.40%,"7,91%",Camboja Camboja (16 718 965)
3,4,Bahia,14 141 626,14 016 906,+0.89%,"6,96%",Zimbabwe (14 862 924)
4,5,Paraná,11 444 380,10 444 526,+9.57%,"5,64%",Tunísia (11 818 619)
5,6,Rio Grande do Sul,10 882 965,10 693 929,+1.76%,"5,36%",Portugal Portugal (10 343 066)
6,7,Pernambuco,9 058 931,8 796 448,+2.98%,"4,46%",Áustria (9 006 398)
7,8,Ceará,8 794 957,8 452 381,+4.05%,"4,33%",Papua-Nova Guiné (8 947 024)
8,9,Pará Pará,8 121 025,7 581 051,+7.12%,"4,1%",Suíça (8 654 622)
9,10,Santa Catarina,7 610 361,6 248 436,+21.78%,"3,75%",Laos Laos (7 749 595)
10,11,Goiás,7 056 495,6 003 788,+17.51%,"3,47%",Bulgária (6 948 445)
11,12,Maranhão,6 775 805,6 574 789,+3.05%,"3,34%",Bulgária (6 948 445)
12,13,Paraíba,3 974 687,3 766 528,+5.52%,"1,96%",Geórgia (3 989 167)
13,14,Amazonas,3 941 613,3 483 985,+13.12%,"1,94%",Geórgia (3 989 167)
14,15,Espírito Santo,3 833 712,3 514 952,+9.06%,"1,89%",Geórgia (3 989 167)
15,16,Mato Grosso,3 658 649,3 035 122,+20.55%,"1,8%",Geórgia (3 989 167)
16,17,Rio Grande do Norte,3 302 729,3 168 027,+4.24%,"1,63%",Uruguai (3 473 730)
17,18,Piauí,3 271 199,3 118 360,+4.88%,"1,61%",Bósnia e Herzegovina (3 280 819)
18,19,Alagoas,3 127 683,3 120 494,+0.23%,"1,54%",Mónaco (3 278 290)
19,20,Distrito Federal,2 817 381,2 570 160,+9.62%,"1,39%",Armênia (2 963 243)
20,21,Mato Grosso do Sul,2 757 013,2 449 024,+12.56%,"1,36%",Albânia (2 877 797)
21,22,Sergipe,2 209 558,2 068 017,+6.86%,"1,09%",Gabão (2 225 734)
22,23,Rondônia,1 581 196,1 562 409,+1.19%,"0,78%",Bahrein (1 701 575)
23,24,Tocantins,1 511 460,1 383 445,+9.25%,"0,74%",Guiné Equatorial (1 402 985)
24,25,Acre,830 018,733 559,+13.15%,"0,41%",Comores (869 601)
25,26,Amapá,733 759,669 526,+9.56%,"0,36%",Guiné Equatorial (786 552)
26,27,Roraima,636 707,450 479,+41.26%,"0,31%",Montenegro (649 335)

In [5]:
# Exibe um resumo conciso do DataFrame `novos_dados`, incluindo o tipo de índice e os tipos de coluna, valores não nulos e uso de memória.
novos_dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Posição                       27 non-null     int64
 1   Unidade federativa            27 non-null     object
 2   População(Censo de 2022)[2]   27 non-null     object
 3   População(Censo de 2010)[3]   27 non-null     object
 4   Mudança                       27 non-null     object
 5   % da pop. total               27 non-null     object
 6   País comparável (habitantes)  27 non-null     object
dtypes: int64(1), object(6)
memory usage: 1.6+ KB

In [6]:
# Remove espaços em branco da coluna "População(Censo de 2022)[2]" do DataFrame `novos_dados`.
novos_dados["População(Censo de 2022)[2]"] = novos_dados["População(Censo de 2022)[2]"].str.replace(" ", "")

# Remove espaços em branco da coluna "População(Censo de 2010)[3]" do DataFrame `novos_dados`.
novos_dados["População(Censo de 2010)[3]"] = novos_dados["População(Censo de 2010)[3]"].str.replace(" ", "")

In [7]:
novos_dados.head(3)

,Posição,Unidade federativa,População(Censo de 2022)[2],População(Censo de 2010)[3],Mudança,% da pop. total,País comparável (habitantes)
0,1,São Paulo,44411238,41262199,+7.63%,"21,88%",Argentina (46 621 847)
1,2,Minas Gerais,20538718,19597330,+4.81%,"10,11%",Burquina Fasso (20 903 273)
2,3,Rio de Janeiro,16054524,15989929,+0.40%,"7,91%",Camboja Camboja (16 718 965)

In [8]:
# Exibe um resumo conciso do DataFrame `novos_dados`, incluindo o tipo de índice e os tipos de coluna, valores não nulos e uso de memória.
novos_dados.info()

#As colunas relacionadas a População ainda estão em formato object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Posição                       27 non-null     int64
 1   Unidade federativa            27 non-null     object
 2   População(Censo de 2022)[2]   27 non-null     object
 3   População(Censo de 2010)[3]   27 non-null     object
 4   Mudança                       27 non-null     object
 5   % da pop. total               27 non-null     object
 6   País comparável (habitantes)  27 non-null     object
dtypes: int64(1), object(6)
memory usage: 1.6+ KB

In [9]:
# Converte o tipo de dados da coluna "População(Censo de 2022)[2]" no DataFrame `novos_dados` para inteiro de 64 bits (int64).
novos_dados["População(Censo de 2022)[2]"] = novos_dados["População(Censo de 2022)[2]"].astype("int64")

# Converte o tipo de dados da coluna "População(Censo de 2010)[3]" no DataFrame `novos_dados` para inteiro de 64 bits (int64).
novos_dados["População(Censo de 2010)[3]"] = novos_dados["População(Censo de 2010)[3]"].astype("int64")

In [10]:
# Exibe um resumo conciso do DataFrame `novos_dados`, incluindo o tipo de índice e os tipos de coluna, valores não nulos e uso de memória.
novos_dados.info()

# As colunas de População agora estão no formato int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Posição                       27 non-null     int64
 1   Unidade federativa            27 non-null     object
 2   População(Censo de 2022)[2]   27 non-null     int64
 3   População(Censo de 2010)[3]   27 non-null     int64
 4   Mudança                       27 non-null     object
 5   % da pop. total               27 non-null     object
 6   País comparável (habitantes)  27 non-null     object
dtypes: int64(3), object(4)
memory usage: 1.6+ KB

In [11]:
# Remove o símbolo de porcentagem (%) da coluna "% da pop. total"
novos_dados["% da pop. total"] = novos_dados["% da pop. total"].str.replace("%", "")

# Substitui vírgulas por pontos para corrigir o formato decimal
novos_dados["% da pop. total"] = novos_dados["% da pop. total"].str.replace(",", ".")

In [12]:
novos_dados.head(3)

,Posição,Unidade federativa,População(Censo de 2022)[2],População(Censo de 2010)[3],Mudança,% da pop. total,País comparável (habitantes)
0,1,São Paulo,44411238,41262199,+7.63%,21.88,Argentina (46 621 847)
1,2,Minas Gerais,20538718,19597330,+4.81%,10.11,Burquina Fasso (20 903 273)
2,3,Rio de Janeiro,16054524,15989929,+0.40%,7.91,Camboja Camboja (16 718 965)

In [13]:
novos_dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Posição                       27 non-null     int64
 1   Unidade federativa            27 non-null     object
 2   População(Censo de 2022)[2]   27 non-null     int64
 3   População(Censo de 2010)[3]   27 non-null     int64
 4   Mudança                       27 non-null     object
 5   % da pop. total               27 non-null     object
 6   País comparável (habitantes)  27 non-null     object
dtypes: int64(3), object(4)
memory usage: 1.6+ KB

In [14]:
# Converte a coluna "% da pop. total" para o tipo float após ajustes de formatação
novos_dados["% da pop. total"] = novos_dados["% da pop. total"].astype(float)

# Exibe um resumo das informações do DataFrame, incluindo o novo tipo de dados da coluna modificada
novos_dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Posição                       27 non-null     int64
 1   Unidade federativa            27 non-null     object
 2   População(Censo de 2022)[2]   27 non-null     int64
 3   População(Censo de 2010)[3]   27 non-null     int64
 4   Mudança                       27 non-null     object
 5   % da pop. total               27 non-null     float64
 6   País comparável (habitantes)  27 non-null     object
dtypes: float64(1), int64(3), object(3)
memory usage: 1.6+ KB

In [15]:
novos_dados.head(3)

,Posição,Unidade federativa,População(Censo de 2022)[2],População(Censo de 2010)[3],Mudança,% da pop. total,País comparável (habitantes)
0,1,São Paulo,44411238,41262199,+7.63%,21.88,Argentina (46 621 847)
1,2,Minas Gerais,20538718,19597330,+4.81%,10.11,Burquina Fasso (20 903 273)
2,3,Rio de Janeiro,16054524,15989929,+0.40%,7.91,Camboja Camboja (16 718 965)